version: '3.8'

services:
    web: &defaults
        image: wfk/server:latest
        restart: unless-stopped

    report_1:
        ports:
            - '21901:21900'
        container_name: report_1
        command: node index.js -s report -m prod
        <<: *defaults

    report_2:
        ports:
            - '21902:21900'
        container_name: report_2
        command: node index.js -s report -m prod
        <<: *defaults
